# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"\x1d\n\x0fGetUsersRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\rGetUsersReply\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User2C\n\x05Users\x12:\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x14.users.GetUsersReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=22
  _globals['_USER']._serialized_end=67
  _globals['_GETUSERSREQUEST']._serialized_start=69
  _globals['_GETUSERSREQUEST']._serialized_end=98
  _globals['_GETUSERSREPLY']._serialized_start=100
  _globals['_GETUSERSREPLY']._serialized_end=143
  _globals['_USERS']._serialized_start=145
  _globals['_USERS']._serialized_end=212
# @@protoc_insertion_point(module_scope)
